# Generated by Django 5.2.5 on 2025-08-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(choices=[('movie', 'Фильм'), ('book', 'Книга'), ('other', 'Другое')], max_length=10, verbose_name='Тип')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
            ],
            options={
                'unique_together': {('title', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('weight', models.IntegerField(default=1, verbose_name='Вес')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('dislikes', models.IntegerField(default=0, verbose_name='Дизлайки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.source')),
            ],
            options={
                'unique_together': {('text', 'source')},
            },
        ),
    ]
