# Generated by Django 5.2.5 on 2025-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='voted_ips',
            field=models.JSONField(blank=True, default=list, verbose_name='Проголосовавшие IP'),
        ),
    ]
